In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
import  pandas as pd
df = pd.DataFrame({'text' :['people like harshil', 'harshil like people', 'people make happy', 'harshil make happy'], 'output': [1,1,0,0]})

In [8]:
df

text  output
0  people like harshil       1
1  harshil like people       1
2    people make happy       0
3   harshil make happy       0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv = CountVectorizer()
bow = cv.fit_transform(df.text)

In [22]:
cv.get_feature_names_out()

array(['happy', 'harshil', 'like', 'make', 'people'], dtype=object)

In [23]:
bow.toarray()

array([[0, 1, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0]])

In [24]:
cv.vocabulary_

{'people': 4, 'like': 2, 'harshil': 1, 'make': 3, 'happy': 0}

In [25]:
cv.transform(["this is harshil people happy"]).toarray()

array([[1, 1, 0, 0, 1]])

In [30]:
cv = CountVectorizer(ngram_range = (1, 2))
bow = cv.fit_transform(df.text)

In [31]:
cv.vocabulary_

{'people': 9,
 'like': 4,
 'harshil': 1,
 'people like': 10,
 'like harshil': 5,
 'harshil like': 2,
 'like people': 6,
 'make': 7,
 'happy': 0,
 'people make': 11,
 'make happy': 8,
 'harshil make': 3}

In [34]:
bow.toarray()

array([[0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0]])

In [29]:
cv.transform(["this is harshil people happy"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0]])

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
tfid = TfidfVectorizer()
tfid.fit_transform(df.text).toarray()

array([[0.        , 0.53256952, 0.65782931, 0.        , 0.53256952],
       [0.        , 0.53256952, 0.65782931, 0.        , 0.53256952],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612],
       [0.61366674, 0.49681612, 0.        , 0.61366674, 0.        ]])

In [43]:
tfid.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.22314355])

In [44]:
tfid.get_feature_names_out()

array(['happy', 'harshil', 'like', 'make', 'people'], dtype=object)